[project]
name = "pdf-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=2.2.0",
    "pydantic>=2.13.5",
    "pymupdf>=1.28.2",
    "pymupdf4llm>=1.28.2",
]

[dependency-groups]
dev = [
    "pikepdf>=9.11.0",
    "pytest>=9.1.1",
]
